package com.hiwhitley.potatoandtomato.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DAILY_EVENT".
 */
public class DailyEvent {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String startTime;
    /** Not-null value. */
    private String endTime;
    /** Not-null value. */
    private String duration;

    public DailyEvent() {
    }

    public DailyEvent(Long id) {
        this.id = id;
    }

    public DailyEvent(Long id, String name, String startTime, String endTime, String duration) {
        this.id = id;
        this.name = name;
        this.startTime = startTime;
        this.endTime = endTime;
        this.duration = duration;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /** Not-null value. */
    public String getDuration() {
        return duration;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDuration(String duration) {
        this.duration = duration;
    }

}
