package com.hiwhitley.potatoandtomato.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TOMATO".
 */
public class Tomato {

    private Long id;
    /** Not-null value. */
    private String content;
    private Integer order;
    private Integer status;
    /** Not-null value. */
    private String time;
    private String reminder;

    public Tomato() {
    }

    public Tomato(Long id) {
        this.id = id;
    }

    public Tomato(Long id, String content, Integer order, Integer status, String time, String reminder) {
        this.id = id;
        this.content = content;
        this.order = order;
        this.status = status;
        this.time = time;
        this.reminder = reminder;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public String getReminder() {
        return reminder;
    }

    public void setReminder(String reminder) {
        this.reminder = reminder;
    }

}
