package com.hiwhitley.potatoandtomato.dao;

import android.database.sqlite.SQLiteDatabase;

import com.hiwhitley.potatoandtomato.bean.Tomato;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tomatoDaoConfig;

    private final TomatoDao tomatoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tomatoDaoConfig = daoConfigMap.get(TomatoDao.class).clone();
        tomatoDaoConfig.initIdentityScope(type);

        tomatoDao = new TomatoDao(tomatoDaoConfig, this);

        registerDao(Tomato.class, tomatoDao);
    }
    
    public void clear() {
        tomatoDaoConfig.getIdentityScope().clear();
    }

    public TomatoDao getTomatoDao() {
        return tomatoDao;
    }

}
